import type { Feature, Geometry, Point } from 'geojson';
import { numericKey } from '../data/countryIso';

// Small states (#104). The 1:110m world atlas the map draws has no shape
// for about thirty scored countries (Singapore, Malta, Bahrain, most
// Pacific and Caribbean island states), so they could not be seen or
// clicked. public/data/small_states.json gives each a representative
// [lon, lat] (generated by scripts/build_small_states.ts from the 1:50m
// atlas), and the renderer draws it as a point marker that joins the
// country paths' data and classes, so fill, tooltip, selection, filters
// and the hatch all apply to it as to any country.

/** Marker radius in screen pixels, held at every zoom level. */
export const SMALL_STATE_RADIUS = 4;

/** One entry of small_states.json: an ISO numeric and its point. */
export interface SmallStatePoint {
  id: string;
  name: string;
  point: [number, number];
}

/** A small state as a map feature: a Point geometry and the dataset name. */
export type SmallStateFeature = Feature<Point, { name: string }>;

function isLonLat(value: unknown): value is [number, number] {
  return Array.isArray(value)
    && value.length === 2
    && value.every(v => typeof v === 'number' && Number.isFinite(v))
    && Math.abs(value[0]) <= 180
    && Math.abs(value[1]) <= 90;
}

/**
 * Coerce a parsed small_states.json into its entries. An entry without an
 * ISO numeric, a name or a valid [lon, lat] is dropped; a file that is
 * missing or malformed gives none (the map then draws only the atlas).
 */
export function normalizeSmallStates(raw: unknown): SmallStatePoint[] {
  const list = (raw as { countries?: unknown } | null)?.countries;
  if (!Array.isArray(list)) return [];
  const out: SmallStatePoint[] = [];
  for (const entry of list) {
    const { id, name, point } = (entry ?? {}) as { id?: unknown; name?: unknown; point?: unknown };
    if (typeof id !== 'string' || !id || typeof name !== 'string' || !name || !isLonLat(point)) continue;
    out.push({ id, name, point: [point[0], point[1]] });
  }
  return out;
}

/**
 * The point features the map draws as markers: one per entry whose country
 * the atlas does not already draw, matched by ISO numeric id (the atlas's
 * geometry ids) or by name once `resolveFeatureNames` has run. The name
 * resolves through `byNumeric` (ISO numeric -> dataset name, as for the
 * atlas geometries), falling back to the file's name.
 */
export function smallStateFeatures(
  points: readonly SmallStatePoint[],
  atlas: readonly Feature<Geometry, { name: string }>[],
  byNumeric: Readonly<Record<string, string>>
): SmallStateFeature[] {
  const atlasIds = new Set(atlas.filter(f => f.id != null).map(f => numericKey(f.id!)));
  const atlasNames = new Set(atlas.map(f => f.properties.name));
  const out: SmallStateFeature[] = [];
  const seen = new Set<string>();
  for (const p of points) {
    const key = numericKey(p.id);
    const name = byNumeric[key] ?? p.name;
    if (atlasIds.has(key) || atlasNames.has(name) || seen.has(name)) continue;
    seen.add(name);
    out.push({
      type: 'Feature',
      id: p.id,
      properties: { name },
      geometry: { type: 'Point', coordinates: [p.point[0], p.point[1]] },
    });
  }
  return out;
}

/**
 * The marker radius in the zoomed map group's units at zoom factor `k`:
 * the group scales by k, so a radius of SMALL_STATE_RADIUS / k draws
 * SMALL_STATE_RADIUS px on screen at every zoom level.
 */
export function smallStateRadius(k: number): number {
  return Number.isFinite(k) && k > 0 ? SMALL_STATE_RADIUS / k : SMALL_STATE_RADIUS;
}

/** The small-state points, or none when the file is missing. */
export async function loadSmallStates(): Promise<SmallStatePoint[]> {
  try {
    const response = await fetch('/data/small_states.json');
    return response.ok ? normalizeSmallStates(await response.json()) : [];
  } catch {
    return [];
  }
}
